"""
Batch-ingest every usable PSA CPH PUF census dataset into its own neighbourhoods csv.
Written by Keagan H. Rankin 2026 IRP project

Closes the loop between the two existing ingest stages: reads the generated manifest
ingest/census_datasets.yaml, writes one ingest config per available dataset into
ingest/ingest_all_config/, runs ph_census_ingest.run_config on each, then verifies every
output has the same schema and value domains as the hand-checked iloilo/mandaue files.

Outputs land in input_files/full_ph_nbs/ (gitignored) as nb_<slug>.csv, one per dataset,
all with in_city = 0 - they exist to widen the sample space, not as cities of interest.

The full batch reads ~5 GB of raw csv and writes ~2 GB, so budget ~45-60 min. Already
ingested datasets are skipped unless --force is passed, making an interrupted run resumable.

Run from the repo root:
    python ingest/ingest_all_ph_census.py                    # configs + ingest + verify
    python ingest/ingest_all_ph_census.py --configs-only     # write the configs, stop
    python ingest/ingest_all_ph_census.py --verify-only      # re-check existing outputs
    python ingest/ingest_all_ph_census.py --force            # re-ingest datasets already done
    python ingest/ingest_all_ph_census.py Iloilo "Cebu City" # only the named datasets
"""

import os
import re
import sys
import time

import pandas as pd
import yaml

# no package tooling in this repo; keep the path shim explicit.
_THIS_DIR = os.path.realpath(os.path.dirname(__file__)) + "/"
_REPO_ROOT = os.path.realpath(_THIS_DIR + "..") + "/"
sys.path.insert(0, _THIS_DIR)
sys.path.insert(0, _REPO_ROOT)

import ph_census_ingest as ingest  # noqa: E402  (imports need the path shim above)
from config import Config  # noqa: E402
from summarize_census_datasets import DEFAULT_ROOT, q  # noqa: E402


####################
### LAYOUT SPEC ###
# the manifest of usable datasets, regenerated by summarize_census_datasets.py.
MANIFEST = _THIS_DIR + "census_datasets.yaml"

# generated configs live in their own subdir, so ph_census_ingest's ingest_*.yaml glob
# (which only looks one level up, in ingest/) still means 'the hand-written configs'.
CONFIG_DIR = _THIS_DIR + "ingest_all_config/"
CONFIG_REL = "ingest_all_config/"  # what run_config gets, resolved against ingest/

# the metadata dictionary sits at the root of the census drive, beside the region folders.
METADATA_PATH = "cph_2020_f2_metadata(dictionary).xlsx"
METADATA_SHEET = "cph_2020_f2_valueset"

# output layout, relative to input_files/.
OUT_SUBDIR = "full_ph_nbs/"
REPORT_NAME = "_ingest_report.csv"

# datasets default to expanding the sample space rather than being a city of interest.
IN_CITY = 0

# datasets to mark as cities of interest instead (in_city = 1), so get_res_current_stock
# counts their rows. add a dataset name here to promote it; everything else stays at 0.
#   Iloilo City: the reference city, whose output must reproduce nb_iloilo.csv exactly.
IN_CITY_DATASETS = {'Iloilo City'}

# datasets whose raw puf files hold corrupt records and need `skip_bad_lines: true`.
# listed explicitly rather than tolerating bad lines everywhere, so a new corrupt file
# still fails loudly instead of being quietly shortened.
#   Isabela: MEMBERS csv lines 763351 and 763365 are two spliced person records
#            (27 and 38 fields against a 31-field header) out of ~1.5M.
BAD_LINE_DATASETS = {'Isabela'}

# known-good outputs the verifier is proven against before it judges the generated ones.
REFERENCES = [("iloilo_scenar_reference/nb_iloilo.csv", 1),
              ("test_mandaue/nb_mandaue.csv", 0)]

# columns the verifier reads back. the rest are metadata labels with no fixed domain.
CHECK_COLS = ['htype', 'm2', 'age_cohort', 'urban', 'n_id', 'pop', 'in_city']

# n_id is REG+PRV+MUN+BGY with REG's leading zero dropped by the Int64 cast, so regions
# 1-9 give 9 digits and 10+ give 10. it must still be constant within one dataset.
N_ID_WIDTHS = {9, 10}


#########################
### CONFIG GENERATION ###
def slug(name):
    """dataset name -> filename-safe slug. 'Mountain Province' -> 'mountain_province'."""
    return re.sub(r'_+', '_', re.sub(r'[^a-z0-9]+', '_', name.lower())).strip('_')


def config_name(ds):
    """the ingest config filename for one manifest dataset."""
    return f"ingest_{slug(ds['name'])}.yaml"


def output_rel(ds):
    """the config's `output` value: a path relative to input_files/."""
    return f"{OUT_SUBDIR}nb_{slug(ds['name'])}.csv"


def output_path(ds):
    """the absolute path the ingest writes to."""
    return Config.input_files + output_rel(ds)


def in_city_for(ds):
    """the dataset's in_city flag: 1 for a city of interest, 0 for sample-space expansion."""
    return 1 if ds['name'] in IN_CITY_DATASETS else IN_CITY


def render_config(ds):
    """
    build the ingest config yaml text for one manifest dataset.

    rendered by hand rather than yaml.dump so the generated files read like the
    hand-written ingest_iloilo.yaml and stay diffable. household/members paths are
    composed from the manifest's own filenames, never from the folder name - Olongapo,
    Pangasinan and Puerto Princesa all depart from the usual convention.
    """
    L = [
        f"# Ingest configuration for {ds['name']} ({ds['region']}).",
        "# GENERATED FILE - do not hand-edit. Regenerate with:",
        "#   python ingest/ingest_all_ph_census.py --configs-only",
        "#",
        f"# Run with: python ingest/ph_census_ingest.py {CONFIG_REL}{config_name(ds)}",
        "",
        "## Raw census data location",
        f"data_root: {q(DEFAULT_ROOT)}",
        "",
        "## Census metadata dictionary",
        "metadata:",
        f"  path: {q(METADATA_PATH)}",
        f"  sheet: {q(METADATA_SHEET)}",
        "",
        "## Output",
        f"output: {q(output_rel(ds))} # relative to input_files/",
        "",
        "## Census datasets",
        "datasets:",
        f"  - name: {slug(ds['name'])}",
        f"    household: {q(ds['dir'] + '/' + ds['household'])}",
        f"    members: {q(ds['dir'] + '/' + ds['members'])}",
        f"    in_city: {in_city_for(ds)} "
        "# 1 = city of interest (used for current stock), 0 = sample-space expansion only",
    ]

    if ds['name'] in BAD_LINE_DATASETS:
        L += [
            "",
            "## This dataset's raw puf files hold corrupt records - see BAD_LINE_DATASETS in",
            "## ingest_all_ph_census.py. The skipped line count is printed on every run.",
            "skip_bad_lines: true",
        ]

    return "\n".join(L) + "\n"


def write_configs(datasets):
    """write an ingest config per dataset, leaving unchanged ones alone."""
    os.makedirs(CONFIG_DIR, exist_ok=True)

    written = 0
    for ds in datasets:
        path = CONFIG_DIR + config_name(ds)
        text = render_config(ds)
        current = open(path, encoding='utf-8').read() if os.path.exists(path) else None

        if text == current:
            continue

        with open(path, 'w', encoding='utf-8') as f:
            f.write(text)
        written += 1

    print(f"  {written} written, {len(datasets) - written} unchanged "
          f"({len(datasets)} configs in {CONFIG_DIR})")


###############
### RUNNING ###
def run_all(datasets, force):
    """
    ingest every dataset, one config at a time.

    already-written outputs are skipped unless force, so an interrupted batch resumes
    where it left off. failures are recorded per dataset rather than aborting the batch,
    matching main.py and ph_census_ingest.main.
    """
    results = {}
    for i, ds in enumerate(datasets, 1):
        name = ds['name']
        print(f"\n[{i}/{len(datasets)}] {name}")

        if os.path.exists(output_path(ds)) and not force:
            print("  skipped, output exists (pass --force to re-ingest)")
            results[name] = ('skipped', 0.0, None)
            continue

        t0 = time.time()
        try:
            # force=True: this runner has already decided skip-vs-overwrite above.
            out = ingest.run_config(CONFIG_REL + config_name(ds), force=True)
            print(f"  wrote {out} in {time.time() - t0:.0f}s")
            results[name] = ('ingested', time.time() - t0, None)
        except Exception as e:
            print(f"  FAILED: {e}")
            results[name] = ('failed', time.time() - t0, f"{type(e).__name__}: {e}")

    return results


#####################
### VERIFICATION ###
def check_domain(nb, col, allowed, problems):
    """flag any non-null value in `col` outside the expected domain."""
    seen = set(nb[col].dropna().unique())
    bad = seen - set(allowed)
    if bad:
        problems.append(f"{col} has unexpected values: {sorted(bad)[:5]}")


def verify_output(path, expect_in_city):
    """
    check one neighbourhoods csv against the schema and value domains of the
    hand-checked iloilo/mandaue outputs. returns (stats, problems).
    """
    stats, problems = {}, []

    if not os.path.exists(path):
        return stats, ["output missing"]

    # schema first: the header must match what sampler.py and the reference files expect.
    header = list(pd.read_csv(path, nrows=0).columns)
    if header != ingest.OUT_COLS:
        problems.append(f"header mismatch: {header}")
        return stats, problems

    nb = pd.read_csv(path, usecols=CHECK_COLS)
    stats['rows'] = len(nb)
    if not len(nb):
        return stats, ["no rows"]

    # value domains: every mapped column may only hold values the spec can produce.
    check_domain(nb, 'htype', ingest.RASMI_TO_RECC.values(), problems)
    check_domain(nb, 'm2', ingest.D1_MEAN.values(), problems)
    check_domain(nb, 'age_cohort', {str(v) for v in ingest.B8_MAP.values()}, problems)
    check_domain(nb, 'urban', ['Urban', 'Rural'], problems)

    # n_id: positive, and one consistent width across the dataset.
    widths = set(nb['n_id'].astype(str).str.len())
    stats['n_ids'] = nb['n_id'].nunique()
    stats['n_id_width'] = sorted(widths)[0] if len(widths) == 1 else sorted(widths)
    if len(widths) != 1 or not widths <= N_ID_WIDTHS:
        problems.append(f"n_id widths {sorted(widths)}, expected one of {sorted(N_ID_WIDTHS)}")

    # population must survive the members merge for every row.
    stats['pop'] = int(nb['pop'].sum())
    if nb['pop'].isna().any():
        problems.append(f"{int(nb['pop'].isna().sum())} rows have no population")
    elif (nb['pop'] <= 0).any():
        problems.append(f"{int((nb['pop'] <= 0).sum())} rows have pop <= 0")

    if list(nb['in_city'].unique()) != [expect_in_city]:
        problems.append(f"in_city is {sorted(nb['in_city'].unique())}, expected {expect_in_city}")

    counts = nb['htype'].value_counts()
    stats.update({f"n_{h}": int(counts.get(h, 0)) for h in ingest.RASMI_TO_RECC.values()})

    # nulls are reported, not failed: unmapped census codes (e.g. B4 code 10, B5 code 8)
    # legitimately land as NaN and ph_census_ingest already warns about them per run.
    nulls = nb.isna().sum()
    stats['null_cols'] = "; ".join(f"{c}={n}" for c, n in nulls.loc[nulls > 0].items())

    return stats, problems


def verify_references():
    """
    run the checker over the two hand-checked outputs first.

    if it can't pass nb_iloilo.csv and nb_mandaue.csv, it isn't measuring 'same format
    as the tests' - so a failure here means the checker is wrong, not the batch.
    """
    print("verifying reference outputs...")

    ok = True
    for rel, in_city in REFERENCES:
        path = Config.input_files + rel
        if not os.path.exists(path):
            print(f"  {rel}: absent, skipped")
            continue

        stats, problems = verify_output(path, in_city)
        flag = "OK" if not problems else "PROBLEM"
        print(f"  {rel}: {flag} ({stats.get('rows', 0)} rows, {stats.get('n_ids', 0)} n_ids)")
        for p in problems:
            print(f"    {p}")
        ok = ok and not problems

    return ok


def verify_all(datasets, results):
    """verify every dataset's output and return the report rows."""
    print("\nverifying outputs...")

    rows = []
    for ds in datasets:
        name = ds['name']
        status, secs, err = results.get(name, ('not run', 0.0, None))

        stats, problems = verify_output(output_path(ds), in_city_for(ds))
        if err:
            problems = [err] + problems

        rows.append({'name': name, 'region': ds['region'], 'output': output_rel(ds),
                     'status': 'ok' if not problems else 'PROBLEM', 'run': status,
                     'seconds': round(secs, 1), **stats,
                     'problems': "; ".join(problems)})

        if problems:
            print(f"  {name}: PROBLEM")
            for p in problems:
                print(f"    {p}")

    return rows


def write_report(rows):
    """write the per-dataset report beside the outputs and print the summary."""
    path = Config.input_files + OUT_SUBDIR + REPORT_NAME
    os.makedirs(os.path.dirname(path), exist_ok=True)
    pd.DataFrame(rows).to_csv(path, index=False)

    ok = [r for r in rows if r['status'] == 'ok']
    print(f"\n{len(ok)}/{len(rows)} datasets verified.")
    print(f"  total rows: {sum(r.get('rows', 0) or 0 for r in ok):,}")
    print(f"  total census population: {sum(r.get('pop', 0) or 0 for r in ok):,}")
    print(f"  report: {path}")

    for r in rows:
        if r['status'] != 'ok':
            print(f"  {r['name']}: {r['problems']}")

    return len(ok) == len(rows)


###########
### CLI ###
def load_manifest():
    """read the available datasets out of the generated manifest."""
    with open(MANIFEST, encoding='utf-8') as stream:
        return yaml.load(stream, Loader=yaml.Loader)['available']


def select(datasets, names):
    """filter the manifest by dataset name or slug. an unmatched name is an error."""
    if not names:
        return datasets

    by_key = {}
    for ds in datasets:
        by_key[ds['name'].lower()] = ds
        by_key[slug(ds['name'])] = ds

    missing = [n for n in names if n.lower() not in by_key and slug(n) not in by_key]
    if missing:
        raise KeyError(f"not in the manifest's available datasets: {missing}")

    picked = [by_key.get(n.lower()) or by_key[slug(n)] for n in names]
    return [ds for ds in datasets if ds in picked]  # keep manifest order


def main(args):
    flags = {a for a in args if a.startswith('--')}
    names = [a for a in args if not a.startswith('--')]

    unknown = flags - {'--configs-only', '--verify-only', '--force'}
    if unknown:
        print(f"unknown flag(s): {sorted(unknown)}")
        return 1

    datasets = select(load_manifest(), names)
    print(f"{len(datasets)} dataset(s) from {MANIFEST}")

    print("\nwriting ingest configs...")
    write_configs(datasets)
    if '--configs-only' in flags:
        return 0

    results = {}
    if '--verify-only' not in flags:
        results = run_all(datasets, force='--force' in flags)

    refs_ok = verify_references()
    rows = verify_all(datasets, results)
    all_ok = write_report(rows)

    return 0 if (refs_ok and all_ok) else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
